Repository gazmull/discord-paginationembed, pull requests merged in 2018-07, with the labels that each got.

#11 Port from master branch (78d4116)
  .gitignore
  .jsdoc.json
  README.md
  docs/CNAME
  docs/Embeds.html
  docs/Embeds.js.html
  docs/FieldsEmbed.html
  docs/FieldsEmbed.js.html
  docs/PaginationEmbed.html
  docs/base_PaginationEmbed.js.html
  docs/global.html
  docs/index.html
  docs/scripts/linenumber.js
  docs/scripts/prettify/Apache-License-2.0.txt
  docs/scripts/prettify/lang-css.js
  docs/scripts/prettify/prettify.js
  docs/styles/jsdoc.css
  docs/styles/prettify.css
  package.json
  src/struct/Embeds.js
  src/struct/FieldsEmbed.js
  src/struct/base/PaginationEmbed.js
  test/bot.js
  test/credentials.sample.js
Labels: breaking change, enhancement

#13 Add ability to delete on timeout
  src/struct/base/PaginationEmbed.js
Labels: enhancement

#17 Allow for disabling of the delete button for public menus
  src/struct/base/PaginationEmbed.js
  test/bot.js
  test/credentials.sample.js
Labels: enhancement

#20 Merged from patch-1
  src/struct/base/PaginationEmbed.js
Labels: bug/error, fixed
